Repository swift-server/swift-kafka-client, pull requests merged in 2024-11, with the labels that each got.

#175 Migrate to GitHub Actions
  .editorconfig
  .flake8
  .github/release.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_label.yml
  .github/workflows/unit_tests.yml
  .licenseignore
  .spi.yml
  .swift-format
  .swiftformat
  .unacceptablelanguageignore
  .yamllint.yml
  Benchmarks/Benchmarks/SwiftKafkaConsumerBenchmarks/KafkaConsumerBenchmark.swift
  Benchmarks/Benchmarks/SwiftKafkaConsumerBenchmarks/Utilities.swift
  Benchmarks/Package.swift
  CONTRIBUTING.md
  CONTRIBUTORS.txt
  Package.swift
  Sources/Kafka/Configuration/KafkaConfiguration+Metrics.swift
  Sources/Kafka/Configuration/KafkaConfiguration+Security.swift
  Sources/Kafka/Configuration/KafkaConsumerConfiguration.swift
  Sources/Kafka/Configuration/KafkaProducerConfiguration.swift
  Sources/Kafka/Configuration/KafkaTopicConfiguration.swift
  Sources/Kafka/Data/String+KafkaContiguousBytes.swift
  Sources/Kafka/ForTesting/RDKafkaClient+Topic.swift
  Sources/Kafka/ForTesting/TestMessages.swift
  Sources/Kafka/KafkaConsumer.swift
  Sources/Kafka/KafkaError.swift
  Sources/Kafka/KafkaOffset.swift
  Sources/Kafka/KafkaProducer.swift
  Sources/Kafka/KafkaProducerEvent.swift
  Sources/Kafka/KafkaProducerMessageID.swift
  Sources/Kafka/RDKafka/RDKafkaClient.swift
  Sources/Kafka/RDKafka/RDKafkaConfig.swift
  Sources/Kafka/RDKafka/RDKafkaTopicConfig.swift
  Sources/Kafka/RDKafka/RDKafkaTopicPartitionList.swift
  Sources/Kafka/Utilities/Duration+Helpers.swift
  Sources/KafkaFoundationCompat/Data+KafkaContiguousBytes.swift
  Tests/IntegrationTests/KafkaTests.swift
  Tests/IntegrationTests/Utilities.swift
  Tests/KafkaTests/KafkaConsumerTests.swift
  Tests/KafkaTests/KafkaProducerTests.swift
  Tests/KafkaTests/Utilities.swift
  dev/test-benchmark-thresholds.sh
  dev/update-benchmark-thresholds.sh
  docker/Dockerfile
  scripts/generate_contributors_list.sh
  scripts/soundness.sh
Labels: semver/minor

#176 Introduce `SendableOpaquePointer`
  Sources/Kafka/RDKafka/RDKafkaClient.swift
  Sources/Kafka/RDKafka/RDKafkaTopicHandles.swift
  Sources/Kafka/Utilities/SendableOpaquePointer.swift
Labels: semver/patch

#171 Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: semver/none

#179 Add headers to `KafkaAcknowledgedMessage`
  Sources/Kafka/KafkaAcknowledgedMessage.swift
  Sources/Kafka/KafkaConsumerMessage.swift
  Sources/Kafka/RDKafka/RDKafkaClient.swift
  Tests/KafkaTests/KafkaProducerTests.swift
Labels: semver/minor

#155 Remove curl dependency and disable OAuth Bearer SASL mechanism
  Package.swift
  Sources/Crdkafka/custom/config/config.h
  Sources/Kafka/Configuration/KafkaConfiguration+Security.swift
Labels: ⚠️ semver/major

#178 Poll for messages using `TaskExecutor`
  Sources/Kafka/KafkaConsumer.swift
  Sources/Kafka/RDKafka/RDKafkaClient.swift
  Sources/Kafka/Utilities/DispatchQueueTaskExecutor.swift
Labels: semver/patch
